# Generated by Django 3.2.5 on 2021-10-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='post_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
