# Generated by Django 3.2.5 on 2021-10-25 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='city1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='return_city', to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='station1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='return_station', to='accounts.station'),
        ),
    ]
