# Generated by Django 3.2.5 on 2021-11-04 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20211027_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='city1',
            field=models.ForeignKey(default='---------', on_delete=django.db.models.deletion.CASCADE, related_name='return_city', to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='station1',
            field=models.ForeignKey(default='---------', on_delete=django.db.models.deletion.CASCADE, related_name='return_station', to='accounts.station'),
        ),
    ]
