# Generated by Django 3.2.5 on 2021-11-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211104_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(max_length=10, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='city1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_city', to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='station1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_station', to='accounts.station'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='protection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.protection'),
        ),
    ]
