# Generated by Django 3.2.5 on 2021-11-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_protection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='station',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
