# Generated by Django 3.2.5 on 2021-11-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211111_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
